---
- name: Generate Inventory Hosts File
  hosts: localhost
  tasks:
    - name: Generate Inventory script
      script: /root/ocp_advanced_deployment_homework/scripts/generate_inventory.sh

- name: refresh inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Refresh in-memory cache
      meta: refresh_inventory
## localhost update ansible
- name: Prepare GUID environment variable across all hosts
  hosts: all
  tasks:
    - name: All GUID env variable
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

- name: Verify Installation and Configuration of Docker
  hosts: nodes
  tasks:
    - name: docker restart
      shell: systemctl restart docker

- name: Verify NFS Shared Volumes on Hosts
  hosts: nfs
  tasks:
    - name: Examine the NFS server to see which NFS volumes are shared
      shell: exportfs

- name: Install packages and config auth
  hosts: localhost
  tasks:
    - name: required packages are present
      yum:
        name:
          - atomic-openshift-clients 
          - openshift-ansible
          - python2-pip
        state: present

- name: Execute the openshift-ansible prerequisites
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: Execute the openshift-ansible Deployer
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: Verify OpenShift Cluster
  hosts: masters[0]
  tasks:
    - name: copy the .kube directory from master1 to your bastion
      fetch:
        src: /root/.kube/config 
        dest: /root/.kube/config 
        flat: yes

- name: Post installation configuration
  hosts: localhost
  tasks:
    - name: make sure you are system:admin
      shell: oc whoami | grep system:admin

- name: Create PVs for Users
  hosts: nfs
  tasks:
    - name: Add shares to exports file
      script: /root/ocp_advanced_deployment_homework/scripts/create_pvs.sh
    - name: Restarting NFS Server...
      shell: systemctl restart nfs-server

- name: Create 25 definitions files for PVs 5G size
  hosts: localhost
  tasks:
    - name:  create files 5g
      script: /root/ocp_advanced_deployment_homework/scripts/pvs_5Gsize.sh
      tags: pvs

- name: Create 25 definitions files for PVs 10G size
  hosts: localhost
  tasks:
    - name:  create files 10g {{ var }}
      script: /root/ocp_advanced_deployment_homework/scripts/pvs_10Gsize.sh
      tags: pvs 

- name: Create all PVs from definitions files
  hosts: localhost
  tasks:
    - name: create all of the defined PVs
      shell: "cat /root/pvs/* | oc apply -f -"
      tags: pvs

      
##
##- name: Fix NFS Persistent Volume Recycling
##
##- name: Smoke Test
##  hosts: localhost
##  tasks:
##    - name: create project smoke-test
##      shell: oc new-project smoke-test
##    - name: Create the Node.js application
##      shell: oc new-app nodejs-mongo-persistent
##    - name: Examine the project status
##      shell: oc status
##    - name: Verify that the storage was set up correctly
##      shell: oc get pvc
##    - name: retrieve the route
##      shell: oc get route
##    - name: Delete your smoke-test project
##      shell: oc delete project smoke-test
##
###### Task app git repo https://github.com/redhat-gpte-devopsautomation/openshift-tasks.git
- name: Jenkins Setup
  hosts: localhost
  tasks:
    - name: jenkins setup
      script: /root/ocp_advanced_deployment_homework/scripts/create_jenkins.sh
      tags: jenkins
##
##- name: HPA configuration on production deployment of openshift-tasks
##  hosts: localhost
##  tasks:
##
##- name: Creation of users for Alpha and Beta clients
##
##- name: Assigning labels to the users according to its group
##
##- name: Setup the environment for Alpha and Beta clients
##
##
##  ....
##